apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-counter
  template:
    metadata:
      labels:
        app: auto-counter
    spec:
      containers:
        - name: app
          image: zedmanny/automobile-counter:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: auto-counter
spec:
  type: NodePort
  selector:
    app: auto-counter
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
