apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-counter
  template:
    metadata:
      labels:
        app: auto-counter
    spec:
      containers:
        - name: app
          image: zedmanny/automobile-counter:latest
          ports:
            - containerPort: 5000
