apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-counter-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-counter-1
  template:
    metadata:
      labels:
        app: auto-counter-1
    spec:
      containers:
        - name: app
          image: zedmanny/automobile-counter:latest
          ports:
            - containerPort: 5000
