apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-hostpath
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing-page-hostpath
  template:
    metadata:
      labels:
        app: landing-page-hostpath
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        hostPath:
          path: /mnt/nano-r5s/landing-page
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page-hostpath-service
spec:
  type: NodePort
  selector:
    app: landing-page-hostpath
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30880  # External port (change if needed)
